// Generated for: console 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.4.0.0
/* eslint-disable */


declare module 'node-api-dotnet' {

	export class Program {
		constructor();

		static Main(args: string[]): void;
	}
}

declare module 'console' {
	export * from 'node-api-dotnet';
}
